1. Added server context.xml. 2. Added SIGTERM handler in boot.sh.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -16,7 +16,8 @@ CACHE_DIR="$(realpath "$2")"
 TOMEE_VERSION="8.0.0"
 TOMEE_HOME="${BUILD_DIR}/tomee"
 JVM_VERSION="1.8"
-JVM_HOME="${BUILD_DIR}/.jdk"
+JDK_HOME="${BUILD_DIR}/.jdk"
+JRE_HOME="${BUILD_DIR}/jre"
 
 MAVEN_REPO_URL="https://repo1.maven.org/maven2"
 APACHE_REPO_URL="${MAVEN_REPO_URL}/org/apache"
@@ -24,6 +25,7 @@ JVM_BPACK_URL="http://heroku-jvm-common.s3.amazonaws.com/jvm-buildpack-common.ta
 TOMEE_URL="${APACHE_REPO_URL}/tomee/apache-tomee/${TOMEE_VERSION}/apache-tomee-${TOMEE_VERSION}-plus.tar.gz"
 BVAL_CORE_URL="${APACHE_REPO_URL}/bval/bval-core/1.1.2/bval-core-1.1.2.jar"
 BVAL_JSR_URL="${APACHE_REPO_URL}/bval/bval-jsr/1.1.2/bval-jsr-1.1.2.jar"
+PGJDBC_URL="${MAVEN_REPO_URL}/org/postgresql/postgresql/42.2.8/postgresql-42.2.8.jar"
 
 
 
@@ -41,11 +43,18 @@ echo " DONE"
 echo -n "${POINTER} Installing OpenJDK ${javaVersion}..."
 install_java "${BUILD_DIR}" "${javaVersion}"
 jdk_overlay "${BUILD_DIR}"
-if [ ! -d "${JVM_HOME}" ]; then
+if [ ! -d "${JDK_HOME}" ]; then
    echo " FAIL"
-   echo "${SPACER} JVM not found in [${JVM_HOME}]"
+   echo "${SPACER} JDK not found in [${JDK_HOME}]"
    exit 1
 fi
+if [ ! -d "${JDK_HOME}/jre" ]; then
+   echo " FAIL"
+   echo "${SPACER} JRE not found in [${JDK_HOME}/jre]"
+   exit 1
+fi
+mv -f "${JDK_HOME}/jre" "${BUILD_DIR}"
+rm -rf "${JDK_HOME}"
 echo " DONE"
 
 
@@ -64,6 +73,7 @@ if [ "${TOMEE_VERSION}" = "8.0.0" ]; then
    curl --silent --remote-name --location "${BVAL_CORE_URL}" &
    curl --silent --remote-name --location "${BVAL_JSR_URL}" &
 fi
+curl --silent --remote-name --location "${PGJDBC_URL}" &
 wait
 echo " DONE"
 
@@ -89,13 +99,25 @@ echo -n "${POINTER} Bundling boot.sh"
 cat >>boot.sh <<EOF
 #!/usr/bin/env sh
 
-export JAVA_HOME="\${HOME}/.jdk"
-export JRE_HOME="\${HOME}/.jdk/jre"
+export JAVA_HOME="\${HOME}/jre"
+export JRE_HOME="\${HOME}/jre"
 export CATALINA_HOME="\${HOME}/tomee"
 export JAVA_OPTS="-Dhttp.port=\${PORT}"
 
+# . "${HOME}/creds/subr.sh"
+
+finalize () {
+   "\${CATALINA_HOME}/bin/catalina.sh" "stop" "360"
+   wait
+   echo "Shutdown successful."
+}
+
+trap "finalize (); exit 0" TERM
+
 "\${CATALINA_HOME}/bin/catalina.sh" "run"
 wait
+echo "Strange: Worker exited by itsel..."
+exit 0
 EOF
 if [ ! -f boot.sh ]; then
    echo " FAIL"
